### PR TITLE
Improve drag & drop from notebook

### PR DESCRIPTION
**Pull request by fcollonval**
This PR fixes partly #87:
- When dropping a cell from a notebook, the widget size is set according to the cell size
- Add button to compact the grid on the top left corner
- Add helper text when there are no widgets in the editor
- Block dragging early - don't wait for the drop to tell the user a cell is not a valid source.

Failed to insert a virtual widget to help placing the cell when drag & dropping it from the notebook

### CODE REVIEW

**Comment by hbcarlos** [comment]
Thanks, looks great!

**Comment by hbcarlos** [comment]
Btw, did you try to update to gridstack v4.0.1 here? What happens, is not working fine?

**Comment by fcollonval** [comment]
> Did you try to update to gridstack v4.0.1 here? What happens, is not working fine?

From my tests, I did not encounter troubles - but I wanted to focus on one feature by PR (what I don't do enough :wink: ).

**Comment by hbcarlos** [comment]
No! I really appreciate these PRs, this is a huge improvement!

**Pull request merged**
