### PR TITLE
Add releaser config

### LINKED ISSUE #147: Adopt the Jupyter Releaser for automated releases
Let's use the Jupyter Releaser to streamline future releases: https://github.com/jupyter-server/jupyter_releaser

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #147 

### TODO

- [x] Add the Releaser config
- [x] Bump version script to update the Python package and npm packages

### CODE REVIEW

**Comment by hbcarlos** [comment]
Maybe we should change the default branch to main.

**Comment by jtpio** [comment]
> Maybe we should change the default branch to main.

Sounds good :+1:

**Comment by jtpio** [comment]
For the bump version script maybe we can keep it simple and have something that takes the version as is and sets the same for both the Python package and the JS packages.

Instead of having the patch / minor / major flow of going through alpha -> beta -> rc -> final.

**Comment by hbcarlos** [comment]
Thanks for working on this Jeremy.

**Comment by jtpio** [comment]
CI is green now.

**Comment by hbcarlos** [comment]
Is it ready?
I can take a look and merge tonight.

**Comment by jtpio** [comment]
For bumping the version with the releaser we can use two options with the current `bump-version.py` script:

- `next`:
  - to increment a patch release, for example from `0.2.0` to `0.2.1`
  - to increment a pre-release, for example from `0.3.0a0` to `0.3.0a1`
- a version directly
  - for example we are currently on `0.2.0` and we can pass `0.3.0a0` directly for the next pre-release, 

JS packages are formatted based on the Python version.

**Comment by jtpio** [comment]
> Is it ready?

I think so. I wanted to do the branch rename to `main` first but don't have access to that section in the settings:

image

**Comment by jtpio** [comment]
Also we need to create a PyPI token for `voila-gridstack` and add it to the `PYPI_TOKEN_MAP`: https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo.html#checklist-for-adoption

**Comment by jtpio** [comment]
Binder link to do a quick smoke test: https://mybinder.org/v2/gh/jtpio/voila-gridstack/releaser?urlpath=voila/tree/examples/scotch_dashboard.ipynb

**Comment by hbcarlos** [comment]
Wow! Thank you so much!
We can rename the branch tomorrow in another PR.

**Pull request merged**
